name: products
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-95.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  google_sign_in: ^5.3.0
  get: 4.6.0
  http: ^0.13.4
  result_type: ^0.1.0
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  pin_code_fields: ^7.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lottieFiles/
  
  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoItalic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf        
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf


  uses-material-design: true

